### ISSUE TITLE
Whiper Model

### ISSUE THREAD

**Issue by Assia55** [rudymohammadbali/Whisper-Transcriber#11]
Hi @rudymohammadbali I' interested in incorporating OpenAI's Whisper model into my project and to i want know how you create custom Whisper,
is there any available resources or documentation to assist with customization.
Best practices for implementation and integration.
Thank you for your assistance.

**Comment by rudymohammadbali** [comment]
Hi, I just read the OpenAI's whisper source code, and modified/added the part I wanted to.
